/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import login.SqlUsuarios;
import login.TipoUsuarios;
import login.Hash;
import login.Registro;
import static vista.Login.frmHome;

/**
 *
 * @author PC
 */
public class RegistroVista extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public RegistroVista() {
        initComponents();
        setLocationRelativeTo(null);
        TipoUsuarios.Tipo(ComboTipo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        labelBestRoute = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btRegistro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtConfirmarContraseña = new javax.swing.JPasswordField();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        ComboTipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(468, 363));
        setResizable(false);
        getContentPane().setLayout(null);

        labelBestRoute.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelBestRoute.setForeground(new java.awt.Color(102, 51, 0));
        labelBestRoute.setText("Best Route");
        getContentPane().add(labelBestRoute);
        labelBestRoute.setBounds(150, -30, 210, 120);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html>Confirmar contraseña</html>");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 140, 81, 60);

        btRegistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btRegistro.setForeground(new java.awt.Color(102, 51, 0));
        btRegistro.setText("Registrar");
        btRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(btRegistro);
        btRegistro.setBounds(210, 290, 87, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(78, 209, 57, 17);

        txtContraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtContraseña);
        txtContraseña.setBounds(179, 110, 201, 30);

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(179, 69, 201, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(78, 75, 53, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(66, 116, 90, 17);

        txtConfirmarContraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtConfirmarContraseña);
        txtConfirmarContraseña.setBounds(179, 162, 201, 30);

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtNombre);
        txtNombre.setBounds(179, 203, 201, 30);

        txtCorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCorreo);
        txtCorreo.setBounds(0, 0, 6, 0);

        ComboTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboTipoActionPerformed(evt);
            }
        });
        getContentPane().add(ComboTipo);
        ComboTipo.setBounds(0, 11, 6, 0);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ColorFondo.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-6, 4, 470, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistroActionPerformed
        // TODO add your handling code here:
        SqlUsuarios modSql = new SqlUsuarios();
        Registro mod = new Registro();
        txtCorreo.setText("noseusa@gmail.com");

        String contra = new String(txtContraseña.getPassword());
        String contraConf = new String(txtConfirmarContraseña.getPassword());
        if (txtUsuario.getText().equals("") || txtNombre.getText().equals("") || txtCorreo.getText().equals("") || contra.equals("") || contraConf.equals("")) {

            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");

        } else {
            if (contra.equals(contraConf)) {

                try {
                    if (modSql.existeUsuario(txtUsuario.getText()) == 0) {

                        if (modSql.validarEmail(txtCorreo.getText())) {

                            String nuevaContra = Hash.sha2(contra);

                            mod.setUsuario(txtUsuario.getText());
                            mod.setContraseña(nuevaContra);
                            mod.setNombre(txtNombre.getText());
                            mod.setCorreo(txtCorreo.getText());
                            String tipo = "Administrado";
                            if(tipo == "Administrado"){
                                
                                mod.setId_tipo(1);
                            
                            }else if (tipo == "Usuario"){
                                mod.setId_tipo(2);
                            }
                            //mod.setId_tipo(1);//Cambiar
                            try {
                                if (modSql.registrar(mod)) {
                                    JOptionPane.showMessageDialog(null, "Registrado!");
                                    limpiar();
                                    this.dispose();
                                    frmHome = new Home(mod);
                                    frmHome.setVisible(true);

                                } else {
                                    JOptionPane.showMessageDialog(null, "Error al guardar");
                                }

                            } catch (SQLException ex) {
                                Logger.getLogger(RegistroVista.class.getName()).log(Level.SEVERE, null, ex);
                            } catch (ClassNotFoundException ex) {
                                Logger.getLogger(RegistroVista.class.getName()).log(Level.SEVERE, null, ex);
                            } catch (IOException ex) {
                                Logger.getLogger(RegistroVista.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "El correo electronico no es válido");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "El usuario ya existe");
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(RegistroVista.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(RegistroVista.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Las contraseñas deben coincidir");
            }
        }


    }//GEN-LAST:event_btRegistroActionPerformed

    private void ComboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTipoActionPerformed
        
    }//GEN-LAST:event_ComboTipoActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    private void limpiar() {
        txtUsuario.setText("");
        txtNombre.setText("");
        txtCorreo.setText("");
        txtContraseña.setText("");
        txtConfirmarContraseña.setText("");
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> ComboTipo;
    private javax.swing.JButton btRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel labelBestRoute;
    private javax.swing.JPasswordField txtConfirmarContraseña;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
